site_name: Azure Functions Doctor
site_description: A diagnostic tool for Python Azure Functions
site_author: Yeongseon Choe
repo_url: https://github.com/yeongseon/azure-functions-doctor

theme:
  name: material

nav:
  - Home: index.md
  - Usage: usage.md
  - Diagnostics: diagnostics.md
  - Development: development.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python: {}
