# ----------------------------------------
# 📦 Build System
# ----------------------------------------
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# ----------------------------------------
# 📦 Hatch Build Configuration
# ----------------------------------------
[tool.hatch.build]
sources = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/azure_functions_doctor"]

# ----------------------------------------
# 🧾 Project Metadata
# ----------------------------------------
[project]
name = "azure-functions-doctor"
version = "0.1.0"
description = "A diagnostic tool for Python Azure Functions"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }

authors = [
  { name = "Yeongseon Choe", email = "yeongseon.choe@gmail.com" }
]

# 📚 Runtime Dependencies
dependencies = [
  "typer",
  "rich",
  "requests"
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Software Development :: Libraries :: Python Modules"
]

# 🧪 Optional Development Dependencies
[project.optional-dependencies]
dev = [
  "black==24.4.2",
  "build",
  "coverage",
  "hatch",
  "mkdocs",
  "mkdocs-material",
  "mkdocstrings[python]",
  "mypy==1.15.0",
  "pre-commit",
  "pytest",
  "ruff==0.11.11",
  "types-requests",
  "tox"
]

# 🖥️ CLI Entrypoint
[project.scripts]
azfunc-doctor = "azure_functions_doctor.cli:cli"

# 🧪 Hatch Environment (Development)
[tool.hatch.envs.default]
features = ["dev"]

[tool.hatch.envs.default.scripts]
format = "ruff format src/azure_functions_doctor tests && black src/azure_functions_doctor tests"
style = "ruff check src/azure_functions_doctor tests"
typecheck = "mypy src/azure_functions_doctor tests"
lint = "hatch run style && hatch run typecheck"
test = "pytest -v tests"
cov = "coverage run -m pytest && coverage report && coverage html"
docs = "mkdocs serve"
precommit = "pre-commit run --all-files"
precommit-install = "pre-commit install"

# 🎨 Code Formatting - Black
[tool.black]
line-length = 120
target-version = ["py39"]

# 🔍 Linting - Ruff
[tool.ruff]
line-length = 120
target-version = "py39"
exclude = [".venv", "build", "dist", "__pycache__"]
src = ["src/azure_functions_doctor"]
fix = true

[tool.ruff.lint]
select = ["E", "F", "I", "B"]

[tool.ruff.lint.isort]
known-first-party = ["azure_functions_doctor"]

# 🧪 Type Checking - Mypy
[tool.mypy]
python_version = "3.9"
strict = true
warn_unused_configs = true
show_error_codes = true
pretty = true
ignore_missing_imports = true

# 🧪 Testing - Pytest
[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

# 📊 Coverage Reporting
[tool.coverage.run]
branch = true
source = ["src/azure_functions_doctor"]

[tool.coverage.report]
show_missing = true
skip_covered = true

# 📚 Docs (MkDocs)
[tool.hatch.envs.docs.scripts]
build = "mkdocs build"
serve = "mkdocs serve"
