# ----------------------------------------
# 📦 Build System
# ----------------------------------------
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# ----------------------------------------
# 🧾 Project Metadata
# ----------------------------------------
[project]
name = "azure-function-doctor"
version = "0.1.0"
description = "A diagnostic tool for Python Azure Functions"
authors = [{ name = "Yeongseon Choe", email = "yeongseon.choe@gmail.com" }]
readme = "README.md"
requires-python = ">=3.9"

# ----------------------------------------
# 📚 Runtime Dependencies
# ----------------------------------------
dependencies = [
    "typer[all]",
    "rich",
    "requests"
]

# ----------------------------------------
# 🔧 Optional (Dev) Dependencies
# ----------------------------------------
[project.optional-dependencies]
dev = [
    "black==24.4.2",  
    "build",
    "coverage",
    "hatch",
    "mkdocs",
    "mkdocs-material",
    "mypy==1.15.0",
    "pre-commit",
    "pytest",
    "ruff==0.11.11",
    "types-requests",
    "tox"
]

# ----------------------------------------
# 🖥️ CLI Entrypoint
# ----------------------------------------
[project.scripts]
azfunc-doctor = "azure_functions_doctor.cli:main"

# ----------------------------------------
# 🐍 Hatch Environment Configuration
# ----------------------------------------
[tool.hatch.envs.default]
features = ["dev"]

[tool.hatch.envs.default.scripts]
format = "ruff format src tests && black src tests"
style = "ruff check src tests"
typecheck = "mypy src tests"
lint = "hatch run style && hatch run typecheck"
test = "pytest -v tests"
cov = "coverage run -m pytest && coverage report && coverage html"
docs = "mkdocs serve"
precommit = "pre-commit run --all-files"
precommit-install = "pre-commit install"

# ----------------------------------------
# 🎨 Code Formatting - Black
# ----------------------------------------
[tool.black]
line-length = 100
target-version = ["py39"]

# ----------------------------------------
# 🔍 Linting - Ruff
# ----------------------------------------
[tool.ruff]
line-length = 100
target-version = "py39"
exclude = [".venv", "build", "dist", "__pycache__"]
src = ["src"]
fix = true

[tool.ruff.lint]
select = ["E", "F", "I", "B"]

[tool.ruff.lint.isort]
known-first-party = ["azure_functions_doctor"]

# ----------------------------------------
# 🧪 Type Checking - Mypy
# ----------------------------------------
[tool.mypy]
python_version = "3.9"
strict = true
warn_unused_configs = true
show_error_codes = true
pretty = true

# ----------------------------------------
# 🧪 Testing - Pytest
# ----------------------------------------
[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

# ----------------------------------------
# 📊 Coverage Reporting
# ----------------------------------------
[tool.coverage.run]
branch = true
source = ["src/azure_functions_doctor"]

[tool.coverage.report]
show_missing = true
skip_covered = true
